# Vietnamese food class name mappings
# Each class maps to: USDA search term, ingredient prompts for Grounding DINO, and typical portion size


USDA_SEARCH_TERMS = {
    "baba-nau-chuoi-dau": "Vietnamese braised duck with banana and bean",
    "banh-bao": "Vietnamese steamed bun bao",
    "banh-beo": "Vietnamese steamed rice cake banh beo",
    "banh-bo": "Vietnamese honeycomb cake banh bo",
    "banh-bot-loc": "Vietnamese tapioca dumpling banh bot loc",
    "banh-can": "Vietnamese mini pancake banh can",
    "banh-canh": "Vietnamese thick noodle soup banh canh",
    "banh-chung": "Vietnamese square sticky rice cake banh chung",
    "banh-cong": "Vietnamese fried cake banh cong",
    "banh-cuon": "Vietnamese steamed rice roll banh cuon",
    "banh-da-cua": "Vietnamese rice noodle with crab banh da cua",
    "banh-da-lon": "Vietnamese pig skin cake banh da lon",
    "banh-duc": "Vietnamese rice cake banh duc",
    "banh-gai": "Vietnamese sweet cake banh gai",
    "banh-giay": "Vietnamese round sticky rice cake banh giay",
    "banh-gio": "Vietnamese pyramid rice dumpling banh gio",
    "banh-hoi": "Vietnamese string rice noodle banh hoi",
    "banh-khot": "Vietnamese mini savory pancake banh khot",
    "banh-la": "Vietnamese leaf cake banh la",
    "banh-mi": "Vietnamese baguette sandwich banh mi",
    "banh-mi-chao": "Vietnamese sandwich with egg banh mi chao",
    "banh-pia": "Vietnamese pastry banh pia",
    "banh-tai-heo": "Vietnamese pig ear cake",
    "banh-tet": "Vietnamese cylindrical sticky rice cake banh tet",
    "banh-tieu": "Vietnamese sesame cake banh tieu",
    "banh-tom-ho-tay": "Vietnamese shrimp cake banh tom",
    "banh-trang-nuong": "Vietnamese grilled rice paper banh trang nuong",
    "banh-troi-nuoc": "Vietnamese sweet floating rice ball banh troi nuoc",
    "banh-trung-thu": "Vietnamese mooncake banh trung thu",
    "banh-u": "Vietnamese sweet cake banh u",
    "banh-xeo": "Vietnamese sizzling crepe banh xeo",
    "bo-kho": "Vietnamese beef stew bo kho",
    "bo-la-lot": "Vietnamese beef in betel leaf bo la lot",
    "bo-luc-lac": "Vietnamese shaking beef bo luc lac",
    "bo-ne": "Vietnamese steak bo ne",
    "bo-nuong-la-lot": "Vietnamese grilled beef in betel leaf",
    "bun-bo-hue": "Vietnamese spicy beef noodle soup bun bo hue",
    "bun-cha": "Vietnamese grilled pork noodle bun cha",
    "bun-cha-ca": "Vietnamese fish cake noodle bun cha ca",
    "bun-dau-mam-tom": "Vietnamese fermented shrimp paste noodle bun dau mam tom",
    "bun-mam": "Vietnamese fermented fish noodle bun mam",
    "bun-rieu": "Vietnamese crab noodle soup bun rieu",
    "bun-thit-nuong": "Vietnamese grilled pork noodle bun thit nuong",
    "ca-kho-to": "Vietnamese braised fish in clay pot ca kho to",
    "ca-loc-nuong": "Vietnamese grilled snakehead fish ca loc nuong",
    "ca-muoi-xoi": "Vietnamese salted fish with sticky rice ca muoi xoi",
    "ca-ri-ga": "Vietnamese chicken curry ca ri ga",
    "ca-sot-ca-chua": "Vietnamese fish in tomato sauce ca sot ca chua",
    "canh-bi-do": "Vietnamese pumpkin soup canh bi do",
    "canh-chua": "Vietnamese sour soup canh chua",
    "canh-cua": "Vietnamese crab soup canh cua",
    "canh-kho-hoa": "Vietnamese dried flower soup",
    "canh-khoai-tim": "Vietnamese beet soup canh khoai tim",
    "cao-lau": "Vietnamese cao lau noodles",
    "cha-ca-la-vong": "Vietnamese turmeric fish cha ca la vong",
    "cha-com": "Vietnamese young rice cake cha com",
    "cha-lui": "Vietnamese grilled pork sausage cha lui",
    "chao-long": "Vietnamese rice porridge with offal chao long",
    "chao-vit": "Vietnamese duck porridge chao vit",
    "com-chay-cha-bong": "Vietnamese crispy rice with pork floss com chay cha bong",
    "com-chien": "Vietnamese fried rice com chien",
    "com-ga-xoi-mo": "Vietnamese chicken rice com ga xoi mo",
    "com-lam": "Vietnamese bamboo tube rice com lam",
    "com-rang-dua-bo": "Vietnamese fried rice with beef com rang dua bo",
    "com-tam": "Vietnamese broken rice com tam",
    "cua-hap-bia": "Vietnamese steamed crab with beer cua hap bia",
    "cut-lon-xao-me": "Vietnamese braised pigeon cut lon xao me",
    "ga-chien-nuoc-mam": "Vietnamese fried chicken with fish sauce ga chien nuoc mam",
    "ga-hap-la-chanh": "Vietnamese steamed chicken with lemon leaf ga hap la chanh",
    "goi-ca-chich": "Vietnamese raw fish salad goi ca chich",
    "goi-cuon": "Vietnamese fresh spring roll goi cuon",
    "hu-tieu": "Vietnamese pork noodle soup hu tieu",
    "khau-nhuc": "Vietnamese braised pork khau nhuc",
    "kho-muc-nuong": "Vietnamese grilled squid kho muc nuong",
    "kho-quet": "Vietnamese braised fish kho quet",
    "lap-xuong": "Vietnamese Chinese sausage lap xuong",
    "luon-om-chuoi-dau": "Vietnamese eel with banana and bean luon om chuoi dau",
    "luon-xao-xa-ot": "Vietnamese stir-fried eel with lemongrass luon xao xa ot",
    "mam-chung": "Vietnamese fermented fish mam chung",
    "mam-tep-chung-thit": "Vietnamese fermented shrimp with pork mam tep chung thit",
    "mi-quang": "Vietnamese turmeric noodle mi quang",
    "mi-xao-gion": "Vietnamese crispy fried noodle mi xao gion",
    "muc-nhoi-thit": "Vietnamese stuffed squid muc noi thit",
    "nam-pia": "Vietnamese five-spice pastry nam pia",
    "nem-chua": "Vietnamese fermented pork roll nem chua",
    "nem-nuong-nha-trang": "Vietnamese grilled pork sausage nem nuong nha trang",
    "nui-xao": "Vietnamese stir-fried macaroni nui xao",
    "oc-buou-hap": "Vietnamese steamed apple snail oc buou hap",
    "oc-huong-xao": "Vietnamese stir-fried baby snail oc huong xao",
    "oc-len-xao-dua": "Vietnamese snail with coconut oc len xao dua",
    "pho": "Vietnamese beef noodle soup pho",
    "rau-muong-xao": "Vietnamese stir-fried water spinach rau muong xao",
    "sup-cua": "Vietnamese crab soup sup cua",
    "tau-hu-nhoi-thit": "Vietnamese stuffed tofu tau hu noi thit",
    "tau-hu-non": "Vietnamese soft tofu dessert tau hu non",
    "thit-dong": "Vietnamese frozen meat thit dong",
    "thit-kho-tau": "Vietnamese braised pork with egg thit kho tau",
    "thit-trau-gac-bep": "Vietnamese dried buffalo meat thit trau gac bep",
    "tiet-canh": "Vietnamese raw blood pudding tiet canh",
    "trung-vit-lon": "Vietnamese balut egg trung vit lon",
    "xoi-gac": "Vietnamese red sticky rice xoi gac",
    "xoi-nep-than": "Vietnamese black sticky rice xoi nep than",
    "xoi-xeo": "Vietnamese mung bean sticky rice xoi xeo",
}

# Grounding DINO text prompts for ingredient detection
# Each prompt ends with "." as required by Grounding DINO
INGREDIENT_PROMPTS = {
    "baba-nau-chuoi-dau": ["duck meat.", "banana.", "green bean.", "braising sauce.", "herb."],
    "banh-bao": ["steamed bun.", "pork filling.", "egg.", "mushroom.", "onion."],
    "banh-beo": ["rice cake.", "shrimp.", "pork crackling.", "scallion oil.", "fish sauce."],
    "banh-bo": ["honeycomb cake.", "coconut.", "pandan.", "sugar."],
    "banh-bot-loc": ["tapioca dumpling.", "shrimp.", "pork.", "scallion.", "fish sauce."],
    "banh-can": ["mini pancake.", "squid.", "shrimp.", "scallion.", "fish sauce."],
    "banh-canh": ["thick noodle.", "pork.", "shrimp.", "fish cake.", "herb.", "broth."],
    "banh-chung": ["sticky rice.", "pork belly.", "mung bean.", "banana leaf."],
    "banh-cong": ["fried cake.", "shrimp.", "mung bean.", "pork.", "vegetable."],
    "banh-cuon": ["steamed rice roll.", "pork.", "wood ear mushroom.", "fried shallot.", "fish sauce.", "herb."],
    "banh-da-cua": ["rice noodle.", "crab.", "pork.", "herb.", "broth."],
    "banh-da-lon": ["pig skin cake.", "coconut.", "pandan.", "sugar."],
    "banh-duc": ["rice cake.", "peanut.", "shrimp.", "scallion.", "fish sauce."],
    "banh-gai": ["sweet cake.", "mung bean.", "pork.", "banana leaf."],
    "banh-giay": ["sticky rice cake.", "mung bean.", "pork."],
    "banh-gio": ["rice dumpling.", "pork.", "wood ear mushroom.", "banana leaf."],
    "banh-hoi": ["string rice noodle.", "grilled pork.", "herb.", "fish sauce.", "scallion oil."],
    "banh-khot": ["mini pancake.", "shrimp.", "pork.", "scallion.", "fish sauce."],
    "banh-la": ["rice cake in leaf.", "pork.", "coconut.", "banana leaf."],
    "banh-mi": ["baguette bread.", "pork pate.", "pickled daikon.", "pickled carrot.", "cilantro.", "jalapeno pepper.", "ham."],
    "banh-mi-chao": ["baguette bread.", "fried egg.", "pork pate.", "butter.", "vegetable."],
    "banh-pia": ["pastry.", "mung bean.", "pork.", "salted egg yolk."],
    "banh-tai-heo": ["pig ear cake.", "pork.", "gelatin."],
    "banh-tet": ["sticky rice cake.", "pork belly.", "mung bean.", "banana leaf."],
    "banh-tieu": ["sesame cake.", "sugar."],
    "banh-tom-ho-tay": ["shrimp cake.", "shrimp.", "sweet potato.", "fish sauce.", "herb."],
    "banh-trang-nuong": ["grilled rice paper.", "egg.", "shrimp.", "scallion.", "pork.", "fish sauce."],
    "banh-troi-nuoc": ["sweet rice ball.", "ginger syrup.", "coconut."],
    "banh-trung-thu": ["mooncake.", "lotus seed.", "egg yolk.", "sugar."],
    "banh-u": ["sweet cake.", "mung bean.", "banana leaf."],
    "banh-xeo": ["rice crepe.", "shrimp.", "pork belly.", "bean sprout.", "mushroom.", "herb."],
    "bo-kho": ["beef.", "carrot.", "potato.", "lemongrass.", "broth.", "herb."],
    "bo-la-lot": ["beef.", "betel leaf.", "lemongrass.", "fish sauce."],
    "bo-luc-lac": ["beef.", "onion.", "pepper.", "fish sauce.", "salad."],
    "bo-ne": ["beef steak.", "egg.", "pate.", "bread.", "butter."],
    "bo-nuong-la-lot": ["beef.", "betel leaf.", "lemongrass.", "fish sauce.", "herb."],
    "bun-bo-hue": ["thick noodle.", "beef shank.", "pork knuckle.", "lemongrass.", "chili.", "herb.", "lime."],
    "bun-cha": ["grilled pork patty.", "pork slice.", "rice vermicelli.", "lettuce.", "fish sauce.", "herb."],
    "bun-cha-ca": ["fish cake.", "rice noodle.", "herb.", "broth."],
    "bun-dau-mam-tom": ["fried tofu.", "fermented shrimp paste.", "pork.", "rice noodle.", "herb."],
    "bun-mam": ["rice noodle.", "fermented fish.", "shrimp.", "pork.", "herb.", "broth."],
    "bun-rieu": ["rice noodle.", "crab.", "tomato.", "tofu.", "herb.", "broth."],
    "bun-thit-nuong": ["grilled pork.", "rice noodle.", "herb.", "fish sauce.", "pickled vegetable."],
    "ca-kho-to": ["fish.", "caramel sauce.", "pepper.", "clay pot."],
    "ca-loc-nuong": ["grilled fish.", "fish sauce.", "herb.", "chili."],
    "ca-muoi-xoi": ["salted fish.", "sticky rice."],
    "ca-ri-ga": ["chicken.", "potato.", "carrot.", "curry.", "coconut milk."],
    "ca-sot-ca-chua": ["fish.", "tomato sauce.", "herb."],
    "canh-bi-do": ["pumpkin.", "pork.", "broth.", "herb."],
    "canh-chua": ["fish.", "pineapple.", "tomato.", "bean sprout.", "herb.", "tamarind."],
    "canh-cua": ["crab.", "spinach.", "egg.", "broth."],
    "canh-kho-hoa": ["dried flower.", "pork.", "broth."],
    "canh-khoai-tim": ["beet.", "pork.", "broth."],
    "cao-lau": ["noodle.", "pork.", "herb.", "crouton.", "fish sauce."],
    "cha-ca-la-vong": ["turmeric fish.", "dill.", "peanut.", "fish sauce.", "rice noodle."],
    "cha-com": ["young rice.", "pork.", "banana leaf."],
    "cha-lui": ["grilled pork sausage.", "herb.", "fish sauce."],
    "chao-long": ["rice porridge.", "pork offal.", "ginger.", "scallion."],
    "chao-vit": ["duck.", "rice porridge.", "ginger.", "herb."],
    "com-chay-cha-bong": ["crispy rice.", "pork floss.", "fish sauce."],
    "com-chien": ["fried rice.", "egg.", "vegetable.", "soy sauce."],
    "com-ga-xoi-mo": ["chicken.", "rice.", "fat.", "fish sauce."],
    "com-lam": ["sticky rice.", "bamboo tube."],
    "com-rang-dua-bo": ["fried rice.", "beef.", "egg.", "vegetable."],
    "com-tam": ["broken rice.", "grilled pork chop.", "egg meatloaf.", "shredded pork.", "fish sauce."],
    "cua-hap-bia": ["crab.", "beer.", "ginger.", "scallion."],
    "cut-lon-xao-me": ["pigeon.", "lemongrass.", "chili.", "fish sauce."],
    "ga-chien-nuoc-mam": ["fried chicken.", "fish sauce.", "garlic."],
    "ga-hap-la-chanh": ["steamed chicken.", "lemon leaf.", "ginger."],
    "goi-ca-chich": ["raw fish.", "herb.", "peanut.", "fish sauce."],
    "goi-cuon": ["rice paper.", "shrimp.", "pork.", "herb.", "vermicelli."],
    "hu-tieu": ["rice noodle.", "pork.", "shrimp.", "liver.", "broth.", "herb."],
    "khau-nhuc": ["pork belly.", "black bean.", "five-spice.", "lemongrass."],
    "kho-muc-nuong": ["grilled squid.", "chili.", "fish sauce."],
    "kho-quet": ["fish.", "caramel sauce.", "pepper.", "scallion."],
    "lap-xuong": ["Chinese sausage.", "rice."],
    "luon-om-chuoi-dau": ["eel.", "banana.", "bean.", "turmeric.", "herb."],
    "luon-xao-xa-ot": ["eel.", "lemongrass.", "chili.", "herb."],
    "mam-chung": ["fermented fish.", "pork.", "vegetable."],
    "mam-tep-chung-thit": ["fermented shrimp.", "pork.", "vegetable."],
    "mi-quang": ["turmeric noodle.", "shrimp.", "pork.", "herb.", "peanut.", "broth."],
    "mi-xao-gion": ["crispy noodle.", "vegetable.", "seafood.", "sauce."],
    "muc-nhoi-thit": ["stuffed squid.", "pork.", "mushroom.", "glass noodle."],
    "nam-pia": ["five-spice pastry.", "pork.", "mung bean."],
    "nem-chua": ["fermented pork.", "garlic.", "chili.", "banana leaf."],
    "nem-nuong-nha-trang": ["grilled pork sausage.", "herb.", "fish sauce.", "rice paper."],
    "nui-xao": ["macaroni.", "vegetable.", "pork.", "soy sauce."],
    "oc-buou-hap": ["apple snail.", "ginger.", "lemongrass.", "fish sauce."],
    "oc-huong-xao": ["baby snail.", "butter.", "garlic.", "chili."],
    "oc-len-xao-dua": ["snail.", "coconut.", "lemongrass.", "chili."],
    "pho": ["rice noodle.", "beef slice.", "broth.", "bean sprout.", "basil.", "lime.", "hoisin sauce."],
    "rau-muong-xao": ["water spinach.", "garlic.", "fish sauce."],
    "sup-cua": ["crab.", "egg.", "corn.", "broth."],
    "tau-hu-nhoi-thit": ["stuffed tofu.", "pork.", "mushroom.", "tomato.", "herb."],
    "tau-hu-non": ["soft tofu.", "sugar syrup.", "coconut."],
    "thit-dong": ["pork.", "broth jelly.", "onion.", "fish sauce."],
    "thit-kho-tau": ["pork belly.", "egg.", "coconut water.", "fish sauce."],
    "thit-trau-gac-bep": ["dried buffalo meat.", "lemon.", "chili.", "herb."],
    "tiet-canh": "blood pudding",
    "trung-vit-lon": ["balut egg.", "salt.", "herb."],
    "xoi-gac": ["red sticky rice.", "gac fruit.", "sugar."],
    "xoi-nep-than": ["black sticky rice.", "sugar.", "coconut."],
    "xoi-xeo": ["sticky rice.", "mung bean.", "pork.", "shallot."],
}

# Typical serving sizes in grams
TYPICAL_PORTION_GRAMS = {
    "baba-nau-chuoi-dau": 350,
    "banh-bao": 120,
    "banh-beo": 150,
    "banh-bo": 100,
    "banh-bot-loc": 200,
    "banh-can": 150,
    "banh-canh": 400,
    "banh-chung": 300,
    "banh-cong": 150,
    "banh-cuon": 250,
    "banh-da-cua": 400,
    "banh-da-lon": 100,
    "banh-duc": 200,
    "banh-gai": 80,
    "banh-giay": 100,
    "banh-gio": 200,
    "banh-hoi": 250,
    "banh-khot": 150,
    "banh-la": 100,
    "banh-mi": 250,
    "banh-mi-chao": 280,
    "banh-pia": 80,
    "banh-tai-heo": 100,
    "banh-tet": 300,
    "banh-tieu": 60,
    "banh-tom-ho-tay": 200,
    "banh-trang-nuong": 80,
    "banh-troi-nuoc": 150,
    "banh-trung-thu": 150,
    "banh-u": 80,
    "banh-xeo": 300,
    "bo-kho": 350,
    "bo-la-lot": 200,
    "bo-luc-lac": 250,
    "bo-ne": 300,
    "bo-nuong-la-lot": 200,
    "bun-bo-hue": 500,
    "bun-cha": 400,
    "bun-cha-ca": 400,
    "bun-dau-mam-tom": 350,
    "bun-mam": 400,
    "bun-rieu": 400,
    "bun-thit-nuong": 350,
    "ca-kho-to": 250,
    "ca-loc-nuong": 300,
    "ca-muoi-xoi": 200,
    "ca-ri-ga": 350,
    "ca-sot-ca-chua": 250,
    "canh-bi-do": 250,
    "canh-chua": 300,
    "canh-cua": 250,
    "canh-kho-hoa": 250,
    "canh-khoai-tim": 250,
    "cao-lau": 300,
    "cha-ca-la-vong": 300,
    "cha-com": 100,
    "cha-lui": 150,
    "chao-long": 350,
    "chao-vit": 350,
    "com-chay-cha-bong": 250,
    "com-chien": 300,
    "com-ga-xoi-mo": 300,
    "com-lam": 200,
    "com-rang-dua-bo": 300,
    "com-tam": 350,
    "cua-hap-bia": 250,
    "cut-lon-xao-me": 200,
    "ga-chien-nuoc-mam": 250,
    "ga-hap-la-chanh": 300,
    "goi-ca-chich": 200,
    "goi-cuon": 120,
    "hu-tieu": 400,
    "khau-nhuc": 200,
    "kho-muc-nuong": 200,
    "kho-quet": 200,
    "lap-xuong": 100,
    "luon-om-chuoi-dau": 300,
    "luon-xao-xa-ot": 200,
    "mam-chung": 200,
    "mam-tep-chung-thit": 200,
    "mi-quang": 350,
    "mi-xao-gion": 300,
    "muc-nhoi-thit": 200,
    "nam-pia": 80,
    "nem-chua": 60,
    "nem-nuong-nha-trang": 150,
    "nui-xao": 300,
    "oc-buou-hap": 200,
    "oc-huong-xao": 200,
    "oc-len-xao-dua": 200,
    "pho": 500,
    "rau-muong-xao": 150,
    "sup-cua": 250,
    "tau-hu-nhoi-thit": 250,
    "tau-hu-non": 150,
    "thit-dong": 200,
    "thit-kho-tau": 250,
    "thit-trau-gac-bep": 150,
    "tiet-canh": 150,
    "trung-vit-lon": 80,
    "xoi-gac": 200,
    "xoi-nep-than": 200,
    "xoi-xeo": 250,
}